//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddParserSrv.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AddParserSrv.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstanbul
        ///Ankara
        ///İzmir
        ///Adana
        ///Adıyaman
        ///Afyonkarahisar
        ///Ağrı
        ///Aksaray
        ///Amasya
        ///Antalya
        ///Ardahan
        ///Artvin
        ///Aydın
        ///Balıkesir
        ///Bartın
        ///Batman
        ///Bayburt
        ///Bilecik
        ///Bingöl
        ///Bitlis
        ///Bolu
        ///Burdur
        ///Bursa
        ///Çanakkale
        ///Çankırı
        ///Çorum
        ///Denizli
        ///Diyarbakır
        ///Düzce
        ///Edirne
        ///Elazığ
        ///Erzincan
        ///Erzurum
        ///Eskişehir
        ///Gaziantep
        ///Giresun
        ///Gümüşhane
        ///Hakkari
        ///Hatay
        ///Iğdır
        ///Isparta
        ///Kahramanmaraş
        ///Karabük
        ///Karaman
        ///Kars
        ///Kastamonu
        ///Kayseri
        ///Kırıkkale
        ///Kırklareli
        ///Kırşehir
        ///Kilis
        ///Kocaeli
        ///Konya
        ///Kütahya
        ///Malatya
        ///Manisa
        ///Mardin
        ///Mer [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Adana
        ///Aladağ
        ///Ceyhan
        ///Çukurova
        ///Feke
        ///İmamoğlu
        ///Karaisalı
        ///Karataş
        ///Kozan
        ///Pozantı
        ///Saimbeyli
        ///Sarıçam
        ///Seyhan
        ///Tufanbeyli
        ///Yumurtalık
        ///Yüreğir
        ///
        /////Adıyaman
        ///Besni
        ///Çelikhan
        ///Gerger
        ///Gölbaşı
        ///Kahta
        ///Samsat
        ///Sincik
        ///Tut
        ///
        /////Afyonkarahisar
        ///Başmakçı
        ///Bayat
        ///Bolvadin
        ///Çay
        ///Çobanlar
        ///Dazkırı
        ///Dinar
        ///Emirdağ
        ///Evciler
        ///Hocalar
        ///İhsaniye
        ///İscehisar
        ///Kızılören
        ///Sandıklı
        ///Sinanpaşa
        ///Sultandağı
        ///Şuhut
        ///
        /////Ağrı
        ///Diyadin
        ///Doğubeyazıt
        ///Eleşkirt
        ///Hamur
        ///Patnos
        ///Taşlıçay
        ///Tutak
        ///
        /////Aksaray
        ///Ağaçören
        ///Eskil
        ///Gülağaç [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Counties {
            get {
                return ResourceManager.GetString("Counties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //İstanbul
        ///&amp;&amp;Beşiktaş
        ///Yıldız
        ///Çırağan
        ///Balmumcu
        ///&amp;&amp;Maltepe
        ///Küçükyalı
        ///&amp;&amp;Şişli
        ///Maslak
        ///&amp;&amp;Kadıköy
        ///Kozyatağı
        ///
        /////Ankara
        ///&amp;&amp;Kızılay
        ///Kolej.
        /// </summary>
        public static string Districts {
            get {
                return ResourceManager.GetString("Districts", resourceCulture);
            }
        }
    }
}
